### ISSUE TITLE
Docker Networking Support

### ISSUE THREAD

**Issue by ambsw-technology** [merll/docker-map#18]
According to the documentation on [links](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/), the feature has been deprecated in favor of a new [networking](https://docs.docker.com/engine/userguide/networking/) option.  Have you looked at this new feature to determine whether (and how) it's supported by docker-map (and docker-fabric)?

**Comment by merll** [comment]
I have been looking into networks, also how to replace the links where appropriate. However I have not yet gotten far with implementing this feature. It would require similar consistency checking as with containers. And for older Docker API versions, the now-deprecated links would still need to work. Nevertheless adding this to docker-map is a top priority.

**Comment by ambsw-technology** [comment]
What "consistency checking"?

**Comment by merll** [comment]
That the Docker network is set up according to the Docker-Map configuration; and that containers are using the correct network. Currently Docker-Map only checks for existence of linked containers.

**Comment by merll** [comment]
Added in version 0.8.0 (beta). Leaving this open until configuration check is complete.
