### ISSUE TITLE
No way to set environment variables on the container

### ISSUE THREAD

**Issue by vijayshan** [merll/docker-map#8]
container configuration like 

'db': {  # Configure container creation and startup
                 'image': 'postgres:9.4.4',
                 'exposes': {
                     5432: 5432
                 },
                 'binds': ['dbdata', "dbinit"],
  'Env': {
                     "PGDATA": "/dbdata"
                 }
                 },

would need the PGDATA environment variable set in the container that is started but after some debugging i realized that the vvariable was being completely ignored. i tried changing it to environment too but that was being ignored too.

**Comment by merll** [comment]
Environment variables are not directly set on container configuration level. Instead they can be set under ``create_options``. In your example, it would look like this:
```
'db': { # Configure container creation and startup
    'image': 'postgres:9.4.4',
    'exposes': {
        5432: 5432
    },
    'binds': ['dbdata', "dbinit"],
    'create_options': {
        'environment': {
            "PGDATA": "/dbdata"
        }
    },
},
```

Same goes for any other option that is defined in [docker-py's docs on the create_container command](http://docker-py.readthedocs.org/en/latest/api/#create_container). Additional options for [HostConfig](http://docker-py.readthedocs.org/en/latest/hostconfig/) such as the ``restart_policy`` can be defined in ``host_config``.
